# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upload.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'upload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cupload.proto\x12\x06upload\",\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0e\n\x06sha256\x18\x02 \x01(\t\"V\n\x11UploadFileRequest\x12 \n\x04info\x18\x01 \x01(\x0b\x32\x10.upload.FileInfoH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"D\n\x12UploadFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x04\x32X\n\rUploadService\x12G\n\nUploadFile\x12\x19.upload.UploadFileRequest\x1a\x1a.upload.UploadFileResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEINFO']._serialized_start=24
  _globals['_FILEINFO']._serialized_end=68
  _globals['_UPLOADFILEREQUEST']._serialized_start=70
  _globals['_UPLOADFILEREQUEST']._serialized_end=156
  _globals['_UPLOADFILERESPONSE']._serialized_start=158
  _globals['_UPLOADFILERESPONSE']._serialized_end=226
  _globals['_UPLOADSERVICE']._serialized_start=228
  _globals['_UPLOADSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
